### ISSUE TITLE
The extension does not work!

### ISSUE THREAD

**Issue by murugappanrm** [joy-yu/vsc-css-snippets#1]
Hi,

The extension does not seem to work at all. Please help.

**Comment by joy-yu** [comment]
@murugappanrm This extension is working normally to me. I can just provide some possible cases for you.
- Check which CSS language are you using. It's support `CSS/SCSS/LESS` currently.
- Check the `Snippet Suggestions` value in VSCode setting. `inline/top` value are recommended, otherwise the css snippets will be hidden or at the bottom.
- Extension conflict. Could you please list your extensions and I'll help to check, you can run the code `code --list-extensions` in bash to get them.

**Comment by murugappanrm** [comment]
Thank you for the help. I figured it out. The documentation needs more elaboration as not all of us are experts and geniuses. We are all learning and good documentation would really help us newbies.

Regards from, Murugappan Ramanathan 

    On Sunday, 5 June 2022 at 03:24:10 pm MYT, joy钰 ***@***.***> wrote:  
 
 


@murugappanrm This extension is working normally to me. I can just provide some possible cases for you.
   
   - Check which CSS language are you using. It's support CSS/SCSS/LESS currently.
   - Check the Snippet Suggestions value in VSCode setting. inline/top value are recommended, otherwise the css snippets will be hidden or at the bottom.
   - Extension conflict. Could you please list your extensions and I'll help to check, you can run the code code --list-extensions in bash to get them.
